{"uuid": "3670dc3d-0fb5-4e57-bd77-8f0c839ff8b4", "children": ["da353706-ae53-406e-9873-7569159c92f5", "003ebabc-53ed-4a0d-93d3-c64dce337a11", "a643f195-47c6-48b0-a574-e8aa00715a3e", "a5df981e-333c-44b3-bd84-cafbfee1a1c3", "a403cb0c-8398-4180-b0c5-7913dea94b80", "09ea920e-33ba-4d5a-937b-26d60e49cf52"], "befores": [{"name": "_Module__pytest_setup_module", "status": "passed", "start": 1588060070516, "stop": 1588060070516}], "afters": [{"name": "_Module__pytest_setup_module::0", "status": "broken", "statusDetails": {"message": "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 10: invalid start byte\n", "trace": "  File \"d:\\python3.8.0\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\python3.8.0\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"d:\\python3.8.0\\lib\\site-packages\\_pytest\\python.py\", line 476, in xunit_setup_module_fixture\n    _call_with_optional_argument(teardown_module, request.module)\n  File \"d:\\python3.8.0\\lib\\site-packages\\_pytest\\python.py\", line 636, in _call_with_optional_argument\n    func()\n  File \"D:\\Python s28\\PythonProject\\Test\\2020年4月28日\\scripts\\test_case.py\", line 107, in teardown_module\n    send_content = f.read()\n  File \"d:\\python3.8.0\\lib\\codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\n"}, "start": 1588060076148, "stop": 1588060079020}], "start": 1588060070516, "stop": 1588060079020}