{"uuid": "73ff8f64-d28e-4df3-9d9c-18605a23c25a", "children": ["c1fee4f9-4b3d-4869-88e4-850a972e3a60", "0ae55811-92e4-4960-a304-0931aad3f6ce", "8e73788c-1a0c-4883-b985-31521fa6ed74", "e9498930-148c-44d7-b835-18c879878f83", "317d999b-9ba8-4bfe-9d45-6a424b6ee2b2", "047fbcaf-d3dc-4ac5-9656-9eeae738fe40"], "befores": [{"name": "_Module__pytest_setup_module", "status": "passed", "start": 1588060260540, "stop": 1588060260540}], "afters": [{"name": "_Module__pytest_setup_module::0", "status": "broken", "statusDetails": {"message": "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 12: invalid start byte\n", "trace": "  File \"d:\\python3.8.0\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"d:\\python3.8.0\\lib\\site-packages\\_pytest\\fixtures.py\", line 800, in _teardown_yield_fixture\n    next(it)\n  File \"d:\\python3.8.0\\lib\\site-packages\\_pytest\\python.py\", line 476, in xunit_setup_module_fixture\n    _call_with_optional_argument(teardown_module, request.module)\n  File \"d:\\python3.8.0\\lib\\site-packages\\_pytest\\python.py\", line 636, in _call_with_optional_argument\n    func()\n  File \"D:\\Python s28\\PythonProject\\Test\\2020年4月28日\\scripts\\test_case.py\", line 107, in teardown_module\n    send_content = f.read()\n  File \"d:\\python3.8.0\\lib\\codecs.py\", line 322, in decode\n    (result, consumed) = self._buffer_decode(data, self.errors, final)\n"}, "start": 1588060267794, "stop": 1588060270102}], "start": 1588060260540, "stop": 1588060270102}